### ISSUE TITLE
more characters to disallow

### ISSUE THREAD

**Issue by pcause** [KNHaw/ThunderbirdObsidianClipper#1]
Looks very interesting,  I have vaults on linux and windows.  I found I needed to add the following to markdownload to disallow:

{}()[]#^&'!;?,'.`

I also don't want spaces in names (hassle in linux).  You might allow the user to add their own list as markdownload does.

**Comment by KNHaw** [comment]
Thank you for the feedback and for pointing me at *markdownload*. As well as your comments on characters to disallow, it's giving me some ideas on how to structure the options. Also, your comment here itself has caught an issue - I can import the email generated by you but I can't link to it from inside another not for some reason. That's gotta get fixed too!

Thank you again!

**Comment by KNHaw** [comment]
Added the changes you suggested. Please see the latest version, v0.2.0.
