### ISSUE TITLE
_MSGCONTENT

### ISSUE THREAD

**Issue by Integral2022** [KNHaw/ThunderbirdObsidianClipper#11]
Hello, I have been using the plugin for a few days. Thank you for the work, I have been looking for something like this. However, the export to Obsidian works, but most emails do not display any message content (_MSGCONTENT). Are there any settings options?

**Comment by KNHaw** [comment]
Thank you for reaching out! Do some messages work and some consistently fail? If that's the case (vs. all messages failing or the same messages can fail or work depending on dumb luck) it may be pure HTML content in specific messages and that isn't supported yet. Right now the add-on only handles pure text without italics, bold, embedded pictures, etc. If that's what's happening then we need to add a warning alert that there's no pure text content to clip, at least until I can add HTML support. Failing without alerting the user is not a good thing.

Please get back to me when convenient so we can get this debugged for you.

Thanks again!

**Comment by KNHaw** [comment]
no response form user for three weeks.losing as
