### ISSUE TITLE
Support CC and BCC

### ISSUE THREAD

**Issue by margech** [KNHaw/ThunderbirdObsidianClipper#14]
Great app. It would be great if CC and BCC are also supported like _MSGRECIPENTS.

**Comment by KNHaw** [comment]
Thanks for reaching out! I have a fix version coming out soon (hopefully this week) but will try to fit this in soon after.

I'm thinking of formatting it as _MSGCC and _MSGBCC. So you could add "CC: _MSGCC" and "BCC: _MSGBCC" and have more insight than just a string of recipients. How does that sound to you? Can you think of a different way of doing it?

**Comment by margech** [comment]
That sounds good for me. I would be happy with this solution. As far as I understand, _MSGRECIPENTS contains only the contacts from To:. With your sugestion you have all the options.

**Comment by KNHaw** [comment]
OK. I just submitted v0.3.2 for approval with this and Issue #15 implemented. It should be pushed to users next week. I will close out this issue when it's live.

**Comment by KNHaw** [comment]
v0.3.2 is out so I'm going to close this issue. Please reopen or create a new issue if there are problems.

Thanks for using ObsidianClipper!
