### ISSUE TITLE
Add ObsidianClipper to the Menu

### ISSUE THREAD

**Issue by lawa42** [KNHaw/ThunderbirdObsidianClipper#18]
Great piece of work, I have a suggestion for a simple enhancement.

Can you add a menu entry to the Message drop down menu in addition to the button in the message pane. 

The reason is fairly simple. I am using the [Thunderbird Conversations](http://github.com/thunderbird-conversations/thunderbird-conversations/wiki) and it changes the message pane and the Obsidian button is missing. Adding Obsidian to the dropdown on right clock menu makes it universally available independent of the other installed extensions.

**Comment by thegreekgeek** [comment]
+1 From me, this would be great.

**Comment by KNHaw** [comment]
It took a little longer than expected, but I have fixed this in V0.4.0. To try it, just right click on an email from your inbox and select the ObsidianClipper option at the bottom of the menu.

I will close this issue in a few days, so please let me know if there are any hiccups.

**Comment by lawa42** [comment]
It works without the Thunderbird Conversations plugin. With it enabled the button is there but nothing happens

**Comment by KNHaw** [comment]
Thanks. I will install that plugin and try to replicate the problem. The only issue is that work has surged at the day job, which is good but limiting my time in my side projects. I'll try to get to it in the next few weeks.

**Comment by KNHaw** [comment]
Fixed in v0.4.2, which was just submitted. Please review when it is available (likely later this week) and confirm if it is fixed.

**Comment by lawa42** [comment]
works. Thanks for the effort
