### ISSUE TITLE
Does not work on Ubuntu 22.04

### ISSUE THREAD

**Issue by sevadah** [KNHaw/ThunderbirdObsidianClipper#2]
Hi,

I tried your plugin on my work laptop with Ubuntu (Thunderbird is installed as snap package, Obsidian as Appimage). When I trigger pluggin from Thunderbird it either opens Obsidian (if it is not already opened) and nothing happens, or if Obsidian is already open, it open's a new Obsidian window and suggests to select the vault.

I have only one vault, which is listed in the plugin settings.

Any ideas what can be done? 
Thanks for wonderful plugin.

**Comment by KNHaw** [comment]
So glad you got it resolved! Please keep me in the loop if yoiu have roblems or ideas for new features.
