### ISSUE TITLE
The mid: link doesn't work in Obsidian (doesn't open Thunderbird)

### ISSUE THREAD

**Issue by jonasdumas** [KNHaw/ThunderbirdObsidianClipper#20]
I could save email with the button into obsidian. Then when i click - inside Obsidian - on the link: 
[Click to open message in email client](mid: REFERENCE )

Nothing happend. It does not open the email on Thunderbird.

**Comment by DaDirnbocher** [comment]
and your OS is?

**Comment by DaDirnbocher** [comment]
its a known (and i guess unsolved) issue that mid doesnt work on macos, see https://github.com/KNHaw/ThunderbirdObsidianClipper/issues/6
