### ISSUE TITLE
Fix and/or Limit size of clipped emails

### ISSUE THREAD

**Issue by KNHaw** [KNHaw/ThunderbirdObsidianClipper#24]
**Background** 
I received a kind email form Michael Heim suggesting an implementation for HTML text (which I am evaluating) that also had an 8000 byte limit to clipped text size. On discussion, he indicated that he was failing to clip 16000 byte messages, so he simply halved that number.

On investigation I found that the 12K message I normally use in my testing ("100 bottles of beer" in text form) clipped without error, but doubling it ("200 bottles..." - 26K) caused the clip to not occur. No errors in debug terminal - just, nothing. 

**Task**
There are Obsidian add-ons for large file support, but I do not want to make Obsidian Clipper dependent on that. Instead, (1) determine the rough upper limit of the clipping (using Windows as my test machine), (2) add an option to specify this number, (3) use this upper limit as the default.

**Comment by boomesq** [comment]
@KNHaw what plugins for large file support are you talking about? i did a search in the community plugins but couldn't find any that seemed to do the job. the clipper is a huge help (thanks so much for your work on it!), but this issue is a real problem for my use case, so i'm in need of a temporary fix

**Comment by KNHaw** [comment]
@boomesq I remember an Obsidian plugin called something like "big file plugin" or "large file plugin" that was useful for the [markdownload](https://github.com/deathau/markdownload) Firefox plugin. But now that I'm actually *looking* for it, I can't find it. 

I'll keep looking as I work on this and will update my results. Please let me know if you happen to find it on your own.

**Comment by KNHaw** [comment]
@boomesq First, I did more digging and my understanding about a "big file plugin" was wrong. I had instead installed the [avanced URI plugin](https://github.com/Vinzent03/obsidian-advanced-uri) which I *thought* supported larger URIs (Obsidian Clipper uses the [Obsidian URI mechanism](https://help.obsidian.md/Extending+Obsidian/Obsidian+URI) to clip emails, so a larger URI would mean larger clipped emails). However, I was wrong. The Advanced URI plugin does a lot, but it does not increase the size of the URI. My apologies for the misunderstanding.

 Second, I did add the feature to limit email size. It is in the v0.4.2 release, which was just submitted and should be live in the next few days. Just so you know, my test message ("200 bottles of beer...") worked with a maximum clip size of 20305 bytes - I would suggest putting the setting to about 20000 bytes. This should not be considered a hard number, though, as [URI encoding](https://en.wikipedia.org/wiki/Percent-encoding) can make one character of text take multiple characters of URI. For example, a single space character encodes to the three characters "%20" in a URI. The limit of URI size on my Windows install seems to be 35717 bytes.

Sorry for the wall of text. There was just a lot of work that went into this one.

In any case, please look at the feature when it goes live and tell me what you think.

**Comment by KNHaw** [comment]
Closing issue as completed
