### ISSUE TITLE
Date format does not adapt to system

### ISSUE THREAD

**Issue by felixmagin** [KNHaw/ThunderbirdObsidianClipper#3]
I absolutely love the idea of the clipper and what it can do already.

Unfortunately, I seem to have issues with the date format of my clippings: The date is always formatted in the shortened German format (d.M.yyyy): Today's date (12 January 2024) becomes "12.1.2024". I already changed my OS's formatting to yyyy-MM-dd ("2024-01-12"). Thunderbird displays the date in this way now, but the clipped emails still appear in the impractical German format.

What makes it extra weird is that before I changed the OS date format, Thunderbird as well as my system date indicator down in the task bar would display the date as dd.MM.yyyy (12.01.2024, with a leading 0 for the month and, where necessary, also the day). The clipper never did that. Therefore I'm not sure if it's a Thunderbird issue.

Dou you have any idea how I could change clipper's behaviour?

Any help would be very much appreciated.

Thanks in advance,
Felix

**Comment by KNHaw** [comment]
I actually came across this in development and considered having a user specified format but never got around to adding it (right now the format is hard coded). I could fold that into the next release and let the user edit a field in the options tab to specify how they want the date or time to look. Would that work for your purposes? 

In theory, I *might* be able to read the system format you've chosen in your operating system but I looked earlier I hit a dead end. I couldn't see that specified anywhere in the API for Add-Ons. I could add that as a long term feature but if the above is OK for you I'll just do that instead.

Please let me know your preference on this.

**Comment by felixmagin** [comment]
Thank you for answering so fast!
If I could specifiy the format, that should work just fine for me. Actually, I would even prefer this solution over a "blind reference" to the operating system's formatting.

Once again, thank you very much for your work!

**Comment by Bsaubolle** [comment]
+1 to the self-assigned format, I would like to use the simple YYYY-MM-DD format, it would be rad to change!  Looking forward to next release.

**Comment by KNHaw** [comment]
FYI, I added this to v0.3.0, which is now in the review queue. It should be processed and go live in the next few days.

**Comment by felixmagin** [comment]
It just went live today and it seems to work perfectly! You made a great tool (Obsidian) amazing. Thank you so much!

**Comment by KNHaw** [comment]
I'm so glad you like it! I'll close out this issue, but if you have any future issues, please make a new one here. 

Thanks again!

**Comment by KNHaw** [comment]
I'm so glad you like it! I'll close out this issue, but if you have any future issues, please make a new one here.

Thanks again!
