### ISSUE TITLE
Replace special characters instead of stripping?

### ISSUE THREAD

**Issue by DaDirnbocher** [KNHaw/ThunderbirdObsidianClipper#4]
How could I use the named  "replace"  option?

![grafik](https://github.com/KNHaw/ThunderbirdObsidianClipper/assets/11771553/bd9e0ddc-0876-4216-bdad-2033b0db1b5c)

Or does "replace" here mean the "use unicorn equivalents"-option?

In this case I would suggest en option to replace this "special" characters by "_" like spaces.

**Comment by KNHaw** [comment]
The current settings are to try to replace characters with Unicode ("Unicorn") equivalents if the "Replace Disallowed Characters" box is set and strip them out if the box is not set or no equivalent can be found. 

It sounds like you'd like a way to instead have an option to just use underscores. I think a user specified character makes more sense (in case someone wants a dash or period or the like). That would leave a three way choice for character replacement: strip character /Unicode replace/user specified replace.

How would you feel about this? Would this meet your needs?

**Comment by DaDirnbocher** [comment]
> That would leave a three way choice for character replacement: strip character /Unicode replace/user specified replace.

yes, that would be fine for me.

**Comment by KNHaw** [comment]
FYI, I added this to v0.3.0, which is now in the review queue. It should be processed and go live in the next few days.

**Comment by KNHaw** [comment]
Gonna close this out as completed.
