### ISSUE TITLE
Add message ID to template fields

### ISSUE THREAD

**Issue by KNHaw** [KNHaw/ThunderbirdObsidianClipper#6]
Per [request by Reddit user jmreagle](https://old.reddit.com/r/ObsidianMD/comments/193c6a9/obsidianclipper_for_thunderbird_is_now_live/khgz6z3/?context=3), add ability to link back to [RFC 2392](https://datatracker.ietf.org/doc/html/rfc2392) message IDs so emails can be reopened form inside Obsidian.

**Comment by reagle** [comment]
Hello, on Reddit you say you implemented this, but I'm not sure what that "this" is. I'm using version 0.2.0 successfully by specifying the "Vault ID" taken from within the obsidian vault picker -- the TB plugin did not work when using the vault name.

Is there a variable for `Message-ID` that I'm supposed to include in the template? And if I click that message-ID, will Thunderbird be opened? While I'd love to have that functionality, I'm not sure if TB/OS can be configured to open URLs that look something like `Message-ID:///foobar555foobar...` ?

**Comment by reagle** [comment]
Understood, thanks for the clarification. "Message-ID:///foobar555foobar" was just something I made up as a placeholder/example, you syntax looks to be correct according to <https://www.rfc-editor.org/rfc/rfc2392#section-2>.

**Comment by KNHaw** [comment]
FYI, I added this to v0.3.0, which is now in the review queue. It should be processed and go live in the next few days.

**Comment by KNHaw** [comment]
Update: v0.3.0 went live yesterday. Please take a peek at the updated version (there's instructions on how to edit your templates on the OPTIONS tab) and let me know how it goes.

**Comment by reagle** [comment]
Thank you. What I'm not sure how to do is associated the "mid:" link type with thunderbird. When I click the "open this link" nothing happens.

<img width="525" alt="SCR-20240127-kfug" src="https://github.com/KNHaw/ThunderbirdObsidianClipper/assets/596814/c6584b16-60c3-4648-8b9c-424a29707784">

**Comment by DaDirnbocher** [comment]
> nothing happens.

Hmm, obviously a dialog is opened. thats more then "nothing happens". Click on "open this link" opens thunderbird (at my computer), I hadnt to do anything for this.

**Comment by reagle** [comment]
Yes, the dialog opens, and when I click "open this link" within the dialog, nothing happens. I'm running macOS 14.2.1 23C71 arm64. I know how to set file type associations, but not sure for URL scheme/protocols. Are you on MacOS?

**Comment by DaDirnbocher** [comment]
> Are you on MacOS?

no. but - if i interpret [this](https://thesweetsetup.com/working-email-urls-macos/) right - you need a message: instead of mid: on macos.

**Comment by KNHaw** [comment]
@DaDirnbocher  - Thank you for looking into this. I wasn't able to reply until now. I did not expect otehr folks to help out here - thank you!

@reagle  - Hmm. "mid:<msgIdLink>" works on Windows with my setup. Per @DaDirnbocher 's suggestion, I tried "message:<msgIdLink>" on Windows and it doesn't seem to work. I'm asked to manually associate the link to the app. That argues that *maybe* we can have some sort of option of to build one link or the other, either by reading the underlying OS or by manually setting selection. The problem is that I don't have a MAC setup and can't test to see if it would fix the issue.

@reagle Could you do me a huge favor and manually edit the link in one of the notes you clipped that are failing? Just replace "mid:" with "message:" in the URL (all lower case, make sure the colon is there) and report back? If it works I can release a fix but if not you have another issue happening that maybe we can debug.

**Comment by DaDirnbocher** [comment]
> - Hmm. "mid:" works on Windows with my setup.

on linux too.

what if you only deliver msgid and leave it to the user/the template to use mid: or message:?

**Comment by KNHaw** [comment]
@DaDirnbocher So, just have the bare msgId and then tell the user "Use '[click here to open](mid:_MSGURI)' in your template and if that doesn't work, try '[click here to open](mid:_MSGURI)'"? I like it. Better than my original idea of forcing either mid/message via an options flag.

**Comment by reagle** [comment]
@DaDirnbocher, that does prompt the MacOS Mail app to open! Unfortunately, I want it to open in Thunderbird and apparently, on MacOS, that's not possible. I've tried a [few options ](https://apple.stackexchange.com/questions/261881/set-default-mail-client-in-macos-without-adding-an-email-account) but didn't get anything to stick. (Thunderbird is set as the default Mail app within Mail.app -- stupid way to configure that -- but setting the app for "mailto:" and "message:" URL schemes is difficult to impossible.)

But that's not your issue, thank you for responding and close when you think appropriate. (I'm going to try a reboot and see if that works....)

**Comment by KNHaw** [comment]
@reagle OK. No sweat. I'll close out. Please let us know if anything else crops up, though. And, as always, thanks for using ObsidianClipper!

**Comment by reagle** [comment]
Thanks. I'm hoping another Mac user might give it a try and know how to set the application for URL schemes.

**Comment by jonasdumas** [comment]
Hi, I encountered the same problem on macOS and found a solution. The `mid:` links are not configured by default on a Mac. Just follow these six steps:

1. Download this plugin:
**RCDefaultApp**
[https://www.rubicode.com/Software/RCDefaultApp/](https://www.rubicode.com/Software/RCDefaultApp/)

2. Open the DMG file; it should appear as a folder.

3. Locate the **RCDefaultApp.prefPane** file and move it into your Library/PreferencePanes/ folder on your Mac.

4. Open **System Preferences** on your Mac and click on the new **SwiftDefaultApp** button.

5. Set Thunderbird as the default app for your email (if it's not already set).

6. Go to the URI Schemes pane and (if it does not exist) add a new entry for **mid** and configure it to open with Thunderbird.

That’s it, ThunderbirdObsidianClipper rocks! 🚀
Thanks to @KNHaw ! 🙏

**Comment by reagle** [comment]
@jonasdumas, thanks for looking into that. I made _some_ progress with [SwiftDefaultApps](https://github.com/Lord-Kamina/SwiftDefaultApps) (a newer/maintained version of RCDefaultApp), which does prompt Thunderbird to open. However:

1. When I create a `mid` URI Scheme I get an error that Thunderbird can't find the message.

<img width="620" alt="SCR-20240426-iifp" src="https://github.com/KNHaw/ThunderbirdObsidianClipper/assets/596814/89c36ac3-f976-46d8-9c74-26fc000a66b7">

2. If I associated Thunderbird with the existing `message` scheme, Thunderbird is opened, but it doesn't do anything (i.e., it doesn't open the message with that ID).

**Comment by jonasdumas** [comment]
Hi @reagle,
I'm not sure i can help, I have no idea what's happening on your system. On my Mac, it works fine.
Here are a few ideas:
- Maybe try SwiftDefaultApp, even if it's an older version, like I did.
- Did you delete the message in the meantime?
- Be sure to keep `mid` in your Obsidian link and in your **SwiftDefaultApp** rule.

**Comment by KNHaw** [comment]
Thanks to all for contributing help on this! I've been busy working on attachment support so I haven't been on it as much. 

I'll fold the suggestions into the user manual this week.
