### ISSUE TITLE
Email Line Breaks on Import

### ISSUE THREAD

**Issue by Bsaubolle** [KNHaw/ThunderbirdObsidianClipper#8]
Love the plugin. One question: When importing the message into Obsidian, the lines breaks are all funky. I have tried with a relatively wide variety of messages. 

I have faced some other line wrap issues in Thunderbird before, specifically when sending emails. It required a small [tweak in the advanced config setting](https://superuser.com/questions/378184/tell-thunderbird-not-to-truncate-or-wrap-lines-when-sending-email) so that Thunderbird wouldn't wrap them unnecessarily. 

Any ideas for a solution?

**Comment by KNHaw** [comment]
Offhand, I'm not sure what could be causing this. I will definitely work on it, although I don't think it'll get into the release I'm targeting for the weekend. Probably the one after that so in the next couple of weeks. In the meantime, I have a couple of questions:

1. Are you running in Linux, Mac, or Windows? Linux to Windows file conversion is notorious for newline issues and I want to rule it out.
2. Is this happening on all messages or just a subset of them? Have you ever managed to get a message clipped without this issue?
3. Would you be comfortable making a test email and providing both the email and the .MD file from your vault? I'm thinking send a multi-line test email to yourself, then modify your templates in the Option tags temporarily to remove email addresses, then clip the email. Then make three files to drop here: a screenshot of the email with the addresses blacked out, a screenshot of the note as it appears in your vault,  and then the MD file dropped here as files for me to examine. I know this is a bother, but doing this would be a great help. I understand if you're not comfortable with it or if it's a bit of work.

Anyways, I'll keep you updated as I work on it. I'm so glad the add-on is useful to you!

**Comment by Bsaubolle** [comment]
Ah, perhaps Linux is the issue. I'm running popOS, I did not know about the issue you mentioned in number 1. I can still do the screenshots if you think it is useful, I'll get to it over the weekend!

Otherwise, the plugin is just what I have been looking for, thank you again.

**Comment by KNHaw** [comment]
I think the screenshots will be useful, so if you can get them to me I'd appreciate it.

**Comment by KNHaw** [comment]
Just wanted to check in - did you ever get those screenshots? I haven't been working this and am not sure if it is still a problem or if you resolved it on your end. Please let me know if it's still an issue or I'll close it out in the next week

**Comment by KNHaw** [comment]
OK. I'm going to close this on the assumption that you found a fix. If that is not the case, please reopen or create a new issue so I can fix it.

Thanks for using ObsidianClipper!
